### ISSUE TITLE
Mutation Support

### ISSUE THREAD

**Issue by DiekoMA** [cainy-a/Anilist4Net#10]
Do you have any plans to add mutations so you can push changes to a users list ?

**Comment by yellowsink** [comment]
Not currently, this library was mostly just intended to pull data down. The reason I say this is that mutation means we'd need a way to authenticate, which is a bit more complexity than I'd wanted to add to this

**Comment by DiekoMA** [comment]
ok, would I be alright forking the project to try and work on that ?

**Comment by yellowsink** [comment]
Go for it!
