### ISSUE TITLE
When will this be uploaded onto nuget?

### ISSUE THREAD

**Issue by unlimitedcoder2** [cainy-a/Anilist4Net#3]
Wanted to use this library but could not find when I searched on nuget. [Search](https://www.nuget.org/packages?q=Anilist4Net)

**Comment by yellowsink** [comment]
Oh my god I completely forgot about NuGet! It's currently midnight in the UK, but I'll upload it tomorrow 👍

**Comment by yellowsink** [comment]
It's on NuGet now! (sorry for being silly and not doing this earlier) https://www.nuget.org/packages/Anilist4Net/
