### ISSUE TITLE
Version Problem 

### ISSUE THREAD

**Issue by DiekoMA** [cainy-a/Anilist4Net#9]
I'm not sure if it's just my system but it says it's built for .net2.1 and I use 4.7 and I can't install it

**Comment by yellowsink** [comment]
Hi! Anilist4Net is built using .NET Standard 2.1.

I am just learning now that compared to .NET standard 2.0, 2.1 dropped support for dotnet 4.x. Can you get your code to run under dotnet 5?

I am currently testing whether this lib will run on standard 2.0. If it works ill release that so you can use it.

**Comment by yellowsink** [comment]
ooh okay i think this might work

![image](https://user-images.githubusercontent.com/19270622/127843334-1080d003-9a30-49d2-abf5-b8917c686b78.png)

**Comment by yellowsink** [comment]
currently testing with dotnet 4.7 (or technically mono because linux but close enough)

**Comment by yellowsink** [comment]
closed by ef23665 - will upload to nuget asap

**Comment by yellowsink** [comment]
https://www.nuget.org/packages/Anilist4Net/1.3.0

**Comment by yellowsink** [comment]
By the way while im here can i suggest you move to .NET 4.8 (the final release of .net framework), or if practical to do so, the new (and awesome!) .NET 5

**Comment by DiekoMA** [comment]
sure, thanks so much I'll update my project

**Comment by yellowsink** [comment]
:+1: glad i could help
